version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.15.1

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - node_modules

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run: yarn
      - save_npm
      - run: yarn lint
      - run: yarn generate

workflows:
  deploy:
    jobs:
      - build
