version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.15.1

jobs:
  init:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run: yarn
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - node_modules
  lint:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: yarn lint
  build:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: yarn generate
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - dist
  deploy_dev:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: npx netlify deploy --dir dist --auth $NETLIFY_ACCESS_TOKEN --site $NETLIFY_SITE_ID | npx strip-ansi > netlify.log
      - store_artifacts:
          path: netlify.log
  deploy_prod:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: npx netlify deploy --prod --dir dist --auth $NETLIFY_ACCESS_TOKEN --site $NETLIFY_SITE_ID | npx strip-ansi > netlify.log
      - store_artifacts:
          path: netlify.log

workflows:
  main:
    jobs:
      - init
      - lint:
          requires:
            - init
      - build:
          requires:
            - init
      - deploy_dev:
          requires:
            - lint
            - build
          filters:
            branches:
              only: /^(?!master).+$/
      - deploy_prod:
          requires:
            - lint
            - build
          filters:
            branches:
              only: master
