version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.15.1

jobs:
  init:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run: yarn
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - node_modules
  build:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: yarn lint
      - run: yarn generate

workflows:
  build:
    jobs:
      - init
      - build
          requires:
            - init
